language: node_js
node_js:
- node
- '12'
env:
  global:
    secure: XiAaUo+3/7DmbvnojQfPxQ7LRHyNnccRBERSGdC0XrO4a5w6YXhahSY6QB4jXAdYnH6QuHiD5MWKQjecRrmdyaleIKW9PdQZB7hVnYYIhvMV9+FhJSncfFKsOp4xVh3gaAQIEu27tay+M8BO1m9TZ9k/MBuaCy0GuAUSvRQ5IUg=
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
